Feature/pool 925 start finalizing production code test on
pooltogether/pooltogether-pool-contracts pull request #254
Opened 2021-02-06 02:55 UTC by aodhgan

Instructions in scripts/fork/governance/runAll.sh

2021-02-06 02:55 UTC, aodhgan commented
@asselstine

2021-02-08 18:55 UTC, asselstine requested changes

2021-02-08 18:55 UTC, asselstine commented on package.json
> +    "hardhat": "^2.0.8",
✂️ 

I don't think this is being used anywhere atm

2021-02-08 18:55 UTC, asselstine commented on scripts/fork/governance/disbursePoolTokens.js
> +const employeeAAddress = require("../../../../governance/deployments/fork/TreasuryVesterForEmployeeA.json").address
Ooooh relative paths....that's not portable.

Should at least set an environment variable to configure the gov project root

2021-02-10 21:34 UTC, aodhgan commented
Closing another PR will superceed

2021-02-10 21:34 UTC, closed without merging