fix non standard ERC20 approve
pooltogether/pooltogether-pool-contracts pull request #288
Opened 2021-03-31 19:45 UTC by steffenix

2021-03-31 20:58 UTC, asselstine requested changes
Good job @steffenix!  Nearly there.  We just need to ensure all test pass: make sure both `yarn test` and `yarn coverage` run without fail.

Coverage must be the same or higher, although I don't think that'll be a problem because it's just one line.

2021-03-31 20:58 UTC, asselstine commented on scripts/fork/usdtDeposit.js
> +    usdt = await ethers.getContractAt('TetherToken', '0xdAC17F958D2ee523a2206206994597C13D831ec7')
It appears that you only use the `approve()` and `transfer()` functions for the USDT token.  Those are both part of ERC20, so you could reuse the standard ERC20 abi:

```javascript
usdt = await ethers.getContractAt('IERC20Upgradeable', '0xdAC17F958D2ee523a2206206994597C13D831ec7')
```

And then you can remove the `TetherToken.sol`.

2021-03-31 21:22 UTC, steffenix commented
I am having issues with tests, master seems to be broken too but I can't read the report on circle ci.

2021-03-31 23:04 UTC, asselstine commented
It appears Coveralls doesn't report broken builds!

- I've added a CircleCI badge, which reports test failures correctly
- I've fixed the tests in the master branch

Please rebase onto the new master!

Thanks for your patience

2021-04-01 07:01 UTC, steffenix commented
rebased, all tests are green

2021-04-01 16:27 UTC, asselstine commented
I can confirm; all tests pass.  Thanks @steffenix!  Good work.

2021-04-01 16:27 UTC, merged