pragma set to 0.6.12 for PrizePool contracts
pooltogether/pooltogether-pool-contracts pull request #303
Opened 2021-06-29 23:44 UTC by kamescg

https://github.com/code-423n4/2021-06-pooltogether-findings/issues/109

2021-07-02 16:41 UTC, PierrickGT approved these changes

2021-07-05 21:42 UTC, asselstine approved these changes

2021-07-05 21:43 UTC, asselstine requested changes
Whoops - just realized we'll want to lock the pragma, so let's remove the carat symbol.

i.e.

`pragma solidity 0.6.12`

2021-07-12 22:15 UTC, kamescg commented
@asselstine removed the carat from pragma decelerations. The thinking was to keep the carat, because the final 0.6.x version ends at 12, but in the event that an a bug fix might be added in `0.6.13` we might want to allow that specific solidity version for external developers.

2021-07-12 22:47 UTC, kamescg commented
All the contract versions are now updated. Shouldn't be any remaining outdated pragma solidity versions.

2021-07-12 22:56 UTC, asselstine approved these changes

2021-07-12 23:26 UTC, merged