Fix/109 for non-prizepool contract
pooltogether/pooltogether-pool-contracts pull request #304
Opened 2021-06-29 23:52 UTC by kamescg

Updates the solidity pragma for all non-prizepool contracts.

2021-07-02 16:42 UTC, PierrickGT approved these changes

2021-07-05 21:42 UTC, asselstine approved these changes

2021-07-05 21:43 UTC, asselstine requested changes
Whoops - just realized we'll want to lock the pragma, so let's remove the carat symbol.

i.e.

`pragma solidity 0.6.12`

2021-07-12 22:48 UTC, kamescg commented
The complete PR will be https://github.com/pooltogether/pooltogether-pool-contracts/pull/303

2021-07-12 22:48 UTC, closed without merging