explicit return values
pooltogether/pooltogether-pool-contracts pull request #307
Opened 2021-06-30 07:33 UTC by kamescg

https://github.com/code-423n4/2021-06-pooltogether-findings/issues/53

2021-07-05 15:46 UTC, PierrickGT requested changes

2021-07-05 15:46 UTC, PierrickGT commented on contracts/prize-pool/PrizePool.sol
> -    return (duration, _burnedCredit);
We should `return (durationSeconds, _burnedCredit);` no? 
Cause I'm not sure `_burnedCredit` will be returned automatically since there is a `_`.

2021-07-05 20:58 UTC, asselstine requested changes

2021-07-05 20:58 UTC, asselstine commented on contracts/prize-pool/PrizePool.sol
> +    uint256 durationSeconds = _estimateCreditAccrualTime(controlledToken, amount, exitFee);
You are shadowing durationSeconds by re-declaring it here.

2021-07-05 20:58 UTC, asselstine commented on contracts/prize-pool/PrizePool.sol
>      (uint256 exitFee, uint256 _burnedCredit) = _calculateEarlyExitFeeLessBurnedCredit(from, controlledToken, amount);
You must assign to burnedCredit, not declare _burnedCredit.  The return value never gets assigned.

2021-07-12 22:06 UTC, asselstine approved these changes

2021-07-12 22:11 UTC, PierrickGT approved these changes

2021-07-12 22:30 UTC, merged