YieldSource check address Audit fix 59
pooltogether/pooltogether-pool-contracts pull request #309
Opened 2021-06-30 19:30 UTC by aodhgan

as per https://github.com/code-423n4/2021-06-pooltogether-findings/issues/59

2021-07-01 16:40 UTC, PierrickGT requested changes

2021-07-01 16:40 UTC, PierrickGT commented on contracts/prize-pool/yield-source/YieldSourcePrizePool.sol
> +    require(address(_yieldSource).isContract(), "YieldSourcePrizePool/yield-address-invalid");
Would make more sense if it was `YieldSourcePrizePool/yield-source-address-invalid` or maybe `YieldSourcePrizePool/yield-source-not-contract-address`

2021-07-05 15:49 UTC, PierrickGT approved these changes

2021-07-05 20:54 UTC, asselstine approved these changes

2021-07-12 18:30 UTC, kamescg commented
merging.

2021-07-12 18:30 UTC, merged