Fix/36 gas optimization
pooltogether/pooltogether-pool-contracts pull request #310
Opened 2021-07-01 05:06 UTC by kamescg

https://github.com/code-423n4/2021-06-pooltogether-findings/issues/36

2021-07-05 15:55 UTC, PierrickGT requested changes

2021-07-05 15:55 UTC, PierrickGT commented on contracts/prize-pool/PrizePool.sol
> +    while (currentToken != _tokenEnd) {
We should keep the same nomenclature for local variables
```suggestion
    address tokenEnd = _tokens.end();
    while (currentToken != tokenEnd) {
```

2021-07-05 23:31 UTC, asselstine approved these changes

2021-07-12 21:43 UTC, PierrickGT approved these changes

2021-07-12 22:06 UTC, asselstine approved these changes

2021-07-12 22:37 UTC, merged