fix(StakePrizePool): check stake token address
pooltogether/pooltogether-pool-contracts pull request #314
Opened 2021-07-01 18:08 UTC by PierrickGT

Issue: https://github.com/code-423n4/2021-06-pooltogether-findings/issues/81

2021-07-05 23:05 UTC, asselstine requested changes

2021-07-05 23:05 UTC, asselstine commented on contracts/prize-pool/stake/StakePrizePool.sol
> +    require(address(_stakeToken).isContract(), "StakePrizePool/stake-token-not-contract-address");
just check non-zero.

2021-07-12 22:10 UTC, asselstine approved these changes

2021-07-12 22:17 UTC, kamescg approved these changes

2021-07-12 22:33 UTC, merged